// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package kkproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderType int32

const (
	OrderType_Precise OrderType = 0
	OrderType_Quick   OrderType = 1
)

var OrderType_name = map[int32]string{
	0: "Precise",
	1: "Quick",
}
var OrderType_value = map[string]int32{
	"Precise": 0,
	"Quick":   1,
}

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}
func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (x *OrderType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OrderType_value, data, "OrderType")
	if err != nil {
		return err
	}
	*x = OrderType(value)
	return nil
}
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_exchange_912902d1b3e71601, []int{0}
}

// *
// Structure representing address for various coin types (BTC, LTC, and etc).
// @used in ExchangeResponse
type ExchangeAddress struct {
	CoinType             *string  `protobuf:"bytes,1,opt,name=coin_type,json=coinType" json:"coin_type,omitempty"`
	Address              *string  `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	DestTag              *string  `protobuf:"bytes,3,opt,name=dest_tag,json=destTag" json:"dest_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeAddress) Reset()         { *m = ExchangeAddress{} }
func (m *ExchangeAddress) String() string { return proto.CompactTextString(m) }
func (*ExchangeAddress) ProtoMessage()    {}
func (*ExchangeAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_912902d1b3e71601, []int{0}
}
func (m *ExchangeAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeAddress.Unmarshal(m, b)
}
func (m *ExchangeAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeAddress.Marshal(b, m, deterministic)
}
func (dst *ExchangeAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeAddress.Merge(dst, src)
}
func (m *ExchangeAddress) XXX_Size() int {
	return xxx_messageInfo_ExchangeAddress.Size(m)
}
func (m *ExchangeAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeAddress proto.InternalMessageInfo

func (m *ExchangeAddress) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *ExchangeAddress) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *ExchangeAddress) GetDestTag() string {
	if m != nil && m.DestTag != nil {
		return *m.DestTag
	}
	return ""
}

type ExchangeResponseV2 struct {
	DepositAddress       *ExchangeAddress `protobuf:"bytes,1,opt,name=deposit_address,json=depositAddress" json:"deposit_address,omitempty"`
	DepositAmount        []byte           `protobuf:"bytes,2,opt,name=deposit_amount,json=depositAmount" json:"deposit_amount,omitempty"`
	Expiration           *int64           `protobuf:"varint,3,opt,name=expiration" json:"expiration,omitempty"`
	QuotedRate           []byte           `protobuf:"bytes,4,opt,name=quoted_rate,json=quotedRate" json:"quoted_rate,omitempty"`
	WithdrawalAddress    *ExchangeAddress `protobuf:"bytes,5,opt,name=withdrawal_address,json=withdrawalAddress" json:"withdrawal_address,omitempty"`
	WithdrawalAmount     []byte           `protobuf:"bytes,6,opt,name=withdrawal_amount,json=withdrawalAmount" json:"withdrawal_amount,omitempty"`
	ReturnAddress        *ExchangeAddress `protobuf:"bytes,7,opt,name=return_address,json=returnAddress" json:"return_address,omitempty"`
	ApiKey               []byte           `protobuf:"bytes,8,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	MinerFee             []byte           `protobuf:"bytes,9,opt,name=miner_fee,json=minerFee" json:"miner_fee,omitempty"`
	OrderId              []byte           `protobuf:"bytes,10,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Type                 *OrderType       `protobuf:"varint,11,opt,name=type,enum=OrderType,def=0" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExchangeResponseV2) Reset()         { *m = ExchangeResponseV2{} }
func (m *ExchangeResponseV2) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponseV2) ProtoMessage()    {}
func (*ExchangeResponseV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_912902d1b3e71601, []int{1}
}
func (m *ExchangeResponseV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponseV2.Unmarshal(m, b)
}
func (m *ExchangeResponseV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponseV2.Marshal(b, m, deterministic)
}
func (dst *ExchangeResponseV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponseV2.Merge(dst, src)
}
func (m *ExchangeResponseV2) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponseV2.Size(m)
}
func (m *ExchangeResponseV2) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponseV2.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponseV2 proto.InternalMessageInfo

const Default_ExchangeResponseV2_Type OrderType = OrderType_Precise

func (m *ExchangeResponseV2) GetDepositAddress() *ExchangeAddress {
	if m != nil {
		return m.DepositAddress
	}
	return nil
}

func (m *ExchangeResponseV2) GetDepositAmount() []byte {
	if m != nil {
		return m.DepositAmount
	}
	return nil
}

func (m *ExchangeResponseV2) GetExpiration() int64 {
	if m != nil && m.Expiration != nil {
		return *m.Expiration
	}
	return 0
}

func (m *ExchangeResponseV2) GetQuotedRate() []byte {
	if m != nil {
		return m.QuotedRate
	}
	return nil
}

func (m *ExchangeResponseV2) GetWithdrawalAddress() *ExchangeAddress {
	if m != nil {
		return m.WithdrawalAddress
	}
	return nil
}

func (m *ExchangeResponseV2) GetWithdrawalAmount() []byte {
	if m != nil {
		return m.WithdrawalAmount
	}
	return nil
}

func (m *ExchangeResponseV2) GetReturnAddress() *ExchangeAddress {
	if m != nil {
		return m.ReturnAddress
	}
	return nil
}

func (m *ExchangeResponseV2) GetApiKey() []byte {
	if m != nil {
		return m.ApiKey
	}
	return nil
}

func (m *ExchangeResponseV2) GetMinerFee() []byte {
	if m != nil {
		return m.MinerFee
	}
	return nil
}

func (m *ExchangeResponseV2) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *ExchangeResponseV2) GetType() OrderType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_ExchangeResponseV2_Type
}

type SignedExchangeResponse struct {
	// Formerly response = 1;
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	ResponseV2           *ExchangeResponseV2 `protobuf:"bytes,3,opt,name=responseV2" json:"responseV2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SignedExchangeResponse) Reset()         { *m = SignedExchangeResponse{} }
func (m *SignedExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*SignedExchangeResponse) ProtoMessage()    {}
func (*SignedExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_exchange_912902d1b3e71601, []int{2}
}
func (m *SignedExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedExchangeResponse.Unmarshal(m, b)
}
func (m *SignedExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedExchangeResponse.Marshal(b, m, deterministic)
}
func (dst *SignedExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedExchangeResponse.Merge(dst, src)
}
func (m *SignedExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_SignedExchangeResponse.Size(m)
}
func (m *SignedExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignedExchangeResponse proto.InternalMessageInfo

func (m *SignedExchangeResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedExchangeResponse) GetResponseV2() *ExchangeResponseV2 {
	if m != nil {
		return m.ResponseV2
	}
	return nil
}

func init() {
	proto.RegisterType((*ExchangeAddress)(nil), "ExchangeAddress")
	proto.RegisterType((*ExchangeResponseV2)(nil), "ExchangeResponseV2")
	proto.RegisterType((*SignedExchangeResponse)(nil), "SignedExchangeResponse")
	proto.RegisterEnum("OrderType", OrderType_name, OrderType_value)
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_exchange_912902d1b3e71601) }

var fileDescriptor_exchange_912902d1b3e71601 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x6b, 0xd4, 0x40,
	0x14, 0xc5, 0x5d, 0xfb, 0x27, 0x9b, 0x1b, 0x9b, 0xdd, 0x8e, 0xa0, 0x91, 0x8a, 0x96, 0x15, 0xb1,
	0x28, 0xe6, 0x61, 0x7d, 0x10, 0x7d, 0x11, 0x0b, 0x0a, 0xb2, 0x0f, 0x6a, 0x2c, 0xbe, 0x86, 0x21,
	0x73, 0x4c, 0x87, 0x74, 0x33, 0xe3, 0x64, 0x62, 0x9b, 0x6f, 0xea, 0xc7, 0x91, 0x4c, 0x76, 0xd2,
	0xa5, 0xd2, 0xc7, 0x39, 0xf7, 0xcc, 0x3d, 0x3f, 0x38, 0x97, 0x62, 0x5c, 0x15, 0xe7, 0xbc, 0x2e,
	0x91, 0x6a, 0xa3, 0xac, 0x5a, 0x14, 0x34, 0xfb, 0xb4, 0x51, 0x3e, 0x0a, 0x61, 0xd0, 0x34, 0xec,
	0x88, 0xc2, 0x42, 0xc9, 0x3a, 0xb7, 0x9d, 0x46, 0x32, 0x39, 0x9e, 0x9c, 0x84, 0xd9, 0xb4, 0x17,
	0xce, 0x3a, 0x0d, 0x96, 0x50, 0xc0, 0x07, 0x5f, 0x72, 0xd7, 0x8d, 0xfc, 0x93, 0x3d, 0xa2, 0xa9,
	0x40, 0x63, 0x73, 0xcb, 0xcb, 0x64, 0x67, 0x18, 0xf5, 0xef, 0x33, 0x5e, 0x2e, 0xfe, 0xee, 0x10,
	0xf3, 0x29, 0x19, 0x1a, 0xad, 0xea, 0x06, 0x3f, 0x97, 0xec, 0x1d, 0xcd, 0x04, 0xb4, 0x6a, 0xa4,
	0xcd, 0xfd, 0xce, 0x3e, 0x2e, 0x5a, 0xce, 0xd3, 0x1b, 0x4c, 0x59, 0xbc, 0x31, 0x7a, 0xc6, 0xe7,
	0x14, 0x8f, 0x5f, 0xd7, 0xaa, 0xad, 0xad, 0xa3, 0xb9, 0x97, 0x1d, 0x78, 0x9f, 0x13, 0xd9, 0x13,
	0x22, 0x5c, 0x69, 0x69, 0xb8, 0x95, 0xaa, 0x76, 0x54, 0x3b, 0xd9, 0x96, 0xc2, 0x9e, 0x52, 0xf4,
	0xbb, 0x55, 0x16, 0x22, 0x37, 0xdc, 0x22, 0xd9, 0x75, 0x3b, 0x68, 0x90, 0x32, 0x6e, 0xc1, 0x3e,
	0x10, 0xbb, 0x94, 0xf6, 0x5c, 0x18, 0x7e, 0xc9, 0x2f, 0x46, 0xca, 0xbd, 0x5b, 0x28, 0x0f, 0xaf,
	0xbd, 0x1e, 0xf4, 0x15, 0x1d, 0x6e, 0x2f, 0x18, 0x58, 0xf7, 0x5d, 0xce, 0x7c, 0xcb, 0x3d, 0xe0,
	0xbe, 0xa5, 0xd8, 0xc0, 0xb6, 0xa6, 0x1e, 0x93, 0x82, 0x5b, 0x92, 0x0e, 0x06, 0x9f, 0x4f, 0x79,
	0x48, 0x01, 0xd7, 0x32, 0xaf, 0xd0, 0x25, 0x53, 0xb7, 0x7b, 0x9f, 0x6b, 0xb9, 0x42, 0xd7, 0x77,
	0xb9, 0x96, 0x35, 0x4c, 0xfe, 0x0b, 0x48, 0x42, 0x37, 0x9a, 0x3a, 0xe1, 0x33, 0xd0, 0x37, 0xa6,
	0x8c, 0x80, 0xc9, 0xa5, 0x48, 0xc8, 0xcd, 0x02, 0xf7, 0xfe, 0x22, 0xd8, 0x0b, 0xda, 0x75, 0xf5,
	0x47, 0xc7, 0x93, 0x93, 0x78, 0x49, 0xe9, 0xd7, 0x5e, 0xef, 0x0f, 0xe0, 0x7d, 0xf0, 0xcd, 0xa0,
	0x90, 0x0d, 0x32, 0x67, 0x58, 0x54, 0xf4, 0xe0, 0x87, 0x2c, 0x6b, 0x88, 0x9b, 0xfd, 0xb2, 0xc7,
	0x14, 0x36, 0xb2, 0xac, 0xb9, 0x6d, 0x0d, 0x36, 0xed, 0x5c, 0x0b, 0xec, 0x0d, 0x91, 0x19, 0x2f,
	0xc1, 0x35, 0x13, 0x2d, 0xef, 0xa7, 0xff, 0x1f, 0x49, 0xb6, 0x65, 0x7b, 0xf9, 0x8c, 0xc2, 0x11,
	0x84, 0x45, 0xe4, 0x51, 0xe6, 0x77, 0x58, 0x48, 0x7b, 0xdf, 0x5b, 0x59, 0x54, 0xf3, 0xc9, 0x69,
	0x4a, 0x47, 0x85, 0x5a, 0xa7, 0x15, 0xa0, 0x2b, 0x74, 0xa9, 0xc0, 0x1f, 0x59, 0xe0, 0xb5, 0xbb,
	0xf6, 0x42, 0x5d, 0x9c, 0xce, 0x56, 0x80, 0x5e, 0xa1, 0xf3, 0x51, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xcb, 0x13, 0x57, 0x12, 0x03, 0x00, 0x00,
}
